name: build pspdev

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #dist: [noble, jammy, focal, bionic]
        #host: [arm64, amd64]
        dist: [noble]
        host: [amd64]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: gen rules
        run: |
          function gen() {
              echo "$1" >> debian/rules
          }
          gen "#!/usr/bin/bash"
          gen "export PSPDEV=/usr/local/pspdev"
          gen "export PATH=/usr/local/pspdev/bin:\$PATH"
          gen "mkdir -p /usr/local/pspdev"
          gen "./build-all.sh"
          cat debian/rules
          chmod +x debian/rules

      - name: gen control
        run: |
          function gen() {
              echo "$1" >> debian/control
          }
          gen "Source: pspdev"
          gen "Maintainer: PSPDEV"
          gen "Section: devel"
          gen "Priority: optional"
          gen "Standards-Version: 4.6.0"
          gen "Build-Depends: texinfo, bison, flex, gettext, libgmp3-dev, libmpfr-dev, libmpc-dev, libusb-dev, libreadline-dev, libcurl4, libcurl4-openssl-dev, libssl-dev, libarchive-dev, libgpgme-dev, python3-pip, python3-venv, cmake, libncurses-dev, automake, pkg-config, wget, git, libtool"
          gen ""
          gen "Package: pspdev"
          gen "Architecture: ${{matrix.host}}"
          gen "Depends: \${shlibs:depends}"
          gen "Description: Sony PSP development toolchain"
          gen ""
          cat debian/control

      - name: install deps
        run: |
          sudo apt update
          sudo apt install -y sbuild ubuntu-dev-tools debhelper
          sudo sbuild-adduser $USER
          
      - name: Setup tmpfs overlay
        run: |
          cat <<EOF > 04tmpfs
          #!/bin/sh

          set -e

          . "\$SETUP_DATA_DIR/common-data"
          . "\$SETUP_DATA_DIR/common-functions"
          . "\$SETUP_DATA_DIR/common-config"

          if [ "\$STAGE" = "setup-start" ]; then
            mount -t tmpfs overlay /var/lib/schroot/union/overlay
          elif [ "\$STAGE" = "setup-recover" ]; then
            mount -t tmpfs overlay /var/lib/schroot/union/overlay
          elif [ "\$STAGE" = "setup-stop" ]; then
            umount -f /var/lib/schroot/union/overlay
          fi
          EOF

          chmod +x 04tmpfs
          sudo mv 04tmpfs /etc/schroot/setup.d/

      - name: Make chroot env with cross-compile
        if: ${{ matrix.host != 'amd64' }}
        run: |
          echo "CHROOT=${{ matrix.dist }}-amd64-${{ matrix.host }}" >> $GITHUB_ENV
          sg sbuild -c 'mk-sbuild --target ${{ matrix.host }} ${{ matrix.dist }}'

      - name: Make chroot env
        if: ${{ matrix.host == 'amd64' }}
        run: |
          echo "CHROOT=${{ matrix.dist }}-${{ matrix.host }}" >> $GITHUB_ENV
          sg sbuild -c 'mk-sbuild ${{ matrix.dist }}'

      - run: sudo sbuild-update --upgrade $CHROOT

      - run: sudo sbuild-apt $CHROOT apt-get install ca-certificates apt-transport-https

      - run: sg sbuild -c 'sbuild --chroot $CHROOT --host ${{ matrix.host }}'

      - run: ls -l

      - name: Release package
        uses: softprops/action-gh-release@master
        with:
          name: ${{matrix.dist}}-${{matrix.host}}-pspdev.deb
          tag_name: ${{matrix.dist}}-${{matrix.host}}-pspdev
          body: |
            psp-dev toolchain
          files: |
            *.deb
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
