name: build pspdev

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #dist: [noble, jammy, focal, bionic]
        dist: [noble]
        host: [arm64, amd64]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: gen rules
        run: |
          function gen() {
              echo "$1" >> debian/rules
          }
          gen "#!/usr/bin/bash"
          gen "echo \"called with \\\"\$@\\\"\""
          gen "exit 0"
          gen "export PSPDEV=/usr/local/pspdev"
          gen "sudo mkdir -p \$PSPDEV"
          gen "sudo chown -R \$USER: \$PSPDEV"
          gen "export PATH=\$PSPDEV/bin:\$PATH"
          gen "git clone https://github.com/pspdev/pspdev"
          gen "cd pspdev"
          gen "./prepare.sh"
          gen "./build-all.sh"
          cat debian/rules
          chmod +x debian/rules

      - name: gen control
        run: |
          function gen() {
              echo "$1" >> debian/control
          }
          gen "Source: pspdev"
          gen "Maintainer: PSPDEV"
          gen "Section: devel"
          gen "Priority: optional"
          gen "Standards-Version: 4.6.0"
          gen "Build-Depends: texinfo, bison, flex, gettext, libgmp3-dev, libmpfr-dev, libmpc-dev, libusb-dev, libreadline-dev, libcurl4, libcurl4-openssl-dev, libssl-dev, libarchive-dev, libgpgme-dev, python3-pip, python3-venv, cmake, libncurses-dev, automake, pkg-config, wget, git, libtool"
          gen "Vcs-Git: https://github.com/pspdev/pspdev.git"
          gen "Vcs-Browser: https://github.com/pspdev/pspdev"
          gen ""
          gen "Package: pspdev"
          gen "Architecture: ${{matrix.host}}"
          gen "Depends: \${shlibs:depends}"
          gen "Description: Sony PSP development toolchain"
          gen ""
          cat debian/control

      - name: install deps
        run: |
          sudo apt update
          sudo apt full-upgrade -y
          sudo apt install -y devscripts equivs build-essential
          sudo mk-build-deps -ir

      - run: |
         debuild -i -us -uc -b -rsudo
         mv ../*.deb . || true

      - run: ls -l

      - name: Release package
        uses: softprops/action-gh-release@master
        with:
          name: ${{matrix.dist}}-${{matrix.host}}-pspdev.deb
          tag_name: ${{matrix.dist}}-${{matrix.host}}-pspdev
          body: |
            psp-dev toolchain
          files: |
            *.deb
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
